### ISSUE TITLE
API use and documentation

### ISSUE THREAD

**Issue by passw0rd123** [jhaals/yopass#19]
In a previous version of yopass there was a rudimental documentation of an API via HTTPS and JSON (see [here](https://github.com/jhaals/yopass/tree/1a39dfcbc6876ddd9e49c3e2bb49573dd121150c)).

Since your last bigger rewrite and the change to the sjcl cryptolibrary this part is missing in the README of the project. 

We consider to automate a secure secret delivery in one of our internal services, so yopass would be a nice solution. (A yopass instance is already running but at this point only used in browser)

While the most of the JSON API is still working as expected...

```bash
# request
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"secret":"secret","Expiration":3600}' \
  https://dasvcjfzrl.execute-api.eu-west-1.amazonaws.com/dev/secret

# response
{"message":"ea75ddc4-bcad-43b7-b767-7546253e8ca8"}
```
... At this point I need to know how the encryption part can be done locally without JS before sending the request to the server. You seem to use the [SJCL](http://bitwiseshiftleft.github.io/sjcl/) defaults. 

But I haven't got this managed so far. Do you have an idea on how an api client can do that?

It would be nice to have this as an official feature back again.

**Comment by jhaals** [comment]
Hi,
Glad to hear that you're using yopass!
You're right that the earlier version had curl examples on how to post the secret. 
The later version does client-side encryption so the secret needs to be encrypted beforehand and that's why I removed the example.
It would be easy to create a CLI in node to do the encryption and uploading to yopass but I haven't had the need.

**Comment by macedogm** [comment]
Hi.
We have created a simple shell and node script to automate calls to Whisper encryption API through CLI.
If someone needs it, we can share the code.
Best regards.

**Comment by passw0rd123** [comment]
Hi @macedogm,
this would be great! 👍

**Comment by macedogm** [comment]
Hi @passw0rd123 .
Here is the code https://github.com/macedogm/whisper-cli-automation .
Fell free to improve it, it is just a quick hack for a need.
Best regards.

**Comment by bahho** [comment]
In case someone is still interested, I worte a small bash snippet to encrypt a string using gpg and send it to yopass:

requirements: gnupg2, jq

`
message="top secret message"
password=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 20 );
echo $password > pass.txt

# encrypt message with pass.txt and replace newlines with "\n"
message=$(echo $message | gpg -a --batch --passphrase-file pass.txt -c  --cipher-algo AES256 | sed ':a;N;$!ba;s/\n/\\n/g' );

payload=$(cat << EOF
{
  "message": "${message}",
  "expiration": 604800 ,
  "one_time": true
}
EOF
)

secret_id=$(curl -s -XPOST  https://api.yopass.se/secret -H 'Content-Type: application/json' -d "${payload}" |  jq -r .message)

echo https://yopass.se/#/s/$secret_id/$password
`

**Comment by dbxclathrope** [comment]
In case folks try to get bahho's version working on a mac (note curl doesn't support OAuth, so if your site uses Google auth, it will complain about no javascript support - look at headless chrome or macedogm idea above that uses node):
`message="top secret message"
#password=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 20 );

#macos compatible:
password=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w20 | head -n1)
echo $password > pass.txt

# encrypt message with pass.txt and replace newlines with "\n"
#message=$(echo $message | gpg -a --batch --passphrase-file pass.txt -c  --cipher-algo AES256 | sed ':a;N;$!ba;s/\n/\\n/g' );

#macos compatible
message=$(echo $message | gpg -a --batch --passphrase-file pass.txt -c  --cipher-algo AES256 | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g');

payload=$(cat << EOF
{
  "message": "${message}",
  "expiration": 604800 ,
  "one_time": true
}
EOF
)

secret_id=$(curl -s -L -XPOST  https://whisper.pp.dropbox.com/secret -H 'Content-Type: application/json' -d "${payload}" |  jq -r .message)

echo https://whisper.pp.dropbox.com/#/s/$secret_id/$password
`

**Comment by gopaldubeyvns** [comment]
I need to encrypt the text locally in java before sending that to yopass, can anyone help with the java code for this ?

**Comment by sergeevabc** [comment]
@MBerdasco, your script returns ' Page Not Found' error, alas.

**Comment by MBerdasco** [comment]
@sergeevabc it is strange, in my local server is still working, but certainly no way on the public one. Do still work the scripts from @dbxclathrope and @bahho? Perhaps there was a new version on public server which broke this?

**Comment by sergeevabc** [comment]
@MBerdasco, I am able to communicate with the server by changing the endpoint address a bit, but cannot grasp how to create an encrypted message without third-party tools (i.e. by means of PowerShell) that the server would accept.

``` console
$ busybox.exe echo -n "hello" | gpg.exe -a --batch --passphrase bDSERrM1IioAyZc7da5l -c --cipher-algo AES256 | busybox.exe sed ":a;N;$!ba;s/\n/\\n/g"
-----BEGIN PGP MESSAGE-----\n\njA0ECQMI+Gw1aXnda1S30joB25REBvKHCQdk2ms77+dd3nfXphDefCCCxCGo1Dgk\nQYb/J6Nr+ceu1VkWLPYyc2K8lLN4Ty9/QFUs\n=q7n6\n-----END PGP MESSAGE-----

$ type secret.json
{
  "message": "-----BEGIN PGP MESSAGE-----\n\njA0ECQMI+Gw1aXnda1S30joB25REBvKHCQdk2ms77+dd3nfXphDefCCCxCGo1Dgk\nQYb/J6Nr+ceu1VkWLPYyc2K8lLN4Ty9/QFUs\n=q7n6\n-----END PGP MESSAGE-----",
  "one_time": false,
  "expiration": 604800
}

$ curl -X POST https://api.yopass.se/secret -H "Content-Type: application/json" -d @secret.json
{"message":"e9268686-92e1-4a11-ae56-f139f3ba8384"}

---

https://yopass.se/#/s/e9268686-92e1-4a11-ae56-f139f3ba8384/bDSERrM1IioAyZc7da5l

hello
```

For example, there is [Invoke-AESEncryption.ps1](https://www.powershellgallery.com/packages/DRTools/4.0.2.3/Content/Functions%5CInvoke-AESEncryption.ps1), a succinct function to encrypt strings via AES CBC. 

``` powershell
$message = Invoke-AESEncryption -Mode Encrypt -Key "bDSERrM1IioAyZc7da5l" -Text "hello"
Write-Host $message

JAc0M8pjihrrctNo0+xbk3khw4heT9Q8eCQ3YteA4X8=
```

If I now send this line to the server, it will generate a link, but it cannot be opened with the specified password.

**Comment by MBerdasco** [comment]
@Hagbart84 as far as I remember I did not configure nothing special on the container, Do you have response from your local when you try to access with browser? 

Regarding $yopassApi, In my local has the same value than $yopassUri and works perfectly:
```
$yopassUri = "https://myyopass.mydomain"
$yopassApi = "https://myyopass.mydomain"
```
Not sure yet why this is different in public yopass (maybe my local is an older version). Anyway, I would try both approaches to see what is the right one for your case.

**Comment by naseemkullah** [comment]
> I need to encrypt the text locally in java before sending that to yopass, can anyone help with the java code for this ?

Re: Java implementation, using PGPainless worked for me:

```java
  private String encryptMessage(String message, String passphrase)
      throws IOException, PGPException {
    Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());

    ByteArrayOutputStream encryptedMessageOutputStream = new ByteArrayOutputStream();

    EncryptionStream encryptionStream =
        PGPainless.encryptAndOrSign()
            .onOutputStream(encryptedMessageOutputStream)
            .withOptions(
                ProducerOptions.encrypt(
                    EncryptionOptions.encryptCommunications()
                        .addPassphrase(Passphrase.fromPassword(passphrase))));

    encryptionStream.write(message.getBytes());
    encryptionStream.close();

    return encryptedMessageOutputStream.toString(java.nio.charset.StandardCharsets.UTF_8.name());
  }
```

**Comment by Fredouye** [comment]
Thanks @bahho for the command lines.

Here's my first try using Ansible (I haven't found a native way of using PGP).

```yaml
---

- name: Encrypt a password using Yopass
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    yopass_url: https://yopass.your.domain
  tasks:
    - name: Create a temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: yopass
      register: temp_dir

    - name: Generate password and decryption key
      ansible.builtin.set_fact:
        password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits', 'punctuation'], length=16) }}"
        decryption_key: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=8) }}"

    - name: Write password to a file
      ansible.builtin.copy:
        content: "{{ password }}"
        dest: "{{ temp_dir.path }}/password.txt"

    - name: Write decryption key to a file
      ansible.builtin.copy:
        content: "{{ decryption_key }}\n"
        dest: "{{ temp_dir.path }}/decryption_key.txt"

    - name: Encrypt password using GPG
      ansible.builtin.shell:
        cmd: cat {{ temp_dir.path }}/password.txt | gpg -a --batch --passphrase-file {{ temp_dir.path }}/decryption_key.txt -c  --cipher-algo AES256
      register: encrypted_password

    - name: Generate crypted message
      ansible.builtin.uri:
        url: '{{ yopass_url }}/secret'
        method: POST
        validate_certs: true
        body_format: json
        body:
          message: "{{ encrypted_password.stdout }}"
          expiration: 604800
          one_time: true
        status_code: 200
        return_content: true
      register: response

    - name: Extract secret ID
      ansible.builtin.set_fact:
        id: "{{ response.content | from_json }}"

    - name: Display URL
      ansible.builtin.debug:
        msg:
          - "Password URL     : {{ yopass_url }}/#/s/{{ id.message  }}"
          - "Decryption key   : {{ decryption_key }}"

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: absent
```
