### ISSUE TITLE
Is it possible to overwrite HTML/CSS?

### ISSUE THREAD

**Issue by josefglatz** [jhaals/yopass#190]
Hi, I want to adopt the FE slightly of the app. Could you provide me some tipps how this could be solved? If I understand correct, the docker image has only compiled templates.

Could you provide me some tipps how to build the Dockerfile by my own with modified frontend related source files? (HTML, CSS, JS)

**Comment by jhaals** [comment]
Hi @josefglatz,

It's correct that the docker file has compiled templates.

You could fork or copy the website folder in-house to do you company/personal changes.
Have a dockerfile that builds the website very similar to today but then just copy the server binary from the public container.
Something like this perhaps. Good luck!

```
FROM node as website
COPY website /website
WORKDIR /website
RUN yarn install && yarn build

FROM yopass:latest
COPY --from=website /website/build /public
ENTRYPOINT ["/yopass"]
```

**Comment by josefglatz** [comment]
## Thank you!! Works!

### Just for reference here the correct Dockerfile:

```
FROM node as website
COPY website /website
WORKDIR /website
RUN yarn install && yarn build

FROM jhaals/yopass:latest
COPY --from=website /website/build /public
ENTRYPOINT ["/yopass"]
```

### Used gitlab-ci.yml

```
image: docker:latest
services:
- docker:dind

stages:
- build
- release

variables:
  TEST_IMAGE: my.registry.domain.at/infrastructure/my-yopass:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: my.registry.domain.at/infrastructure/my-yopass:latest
  PRIVATE_DOCKER_REGISTRY: my.registry.domain.at
  YOPASS_UPSTREAM_VERSION: 6.2.0

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $PRIVATE_DOCKER_REGISTRY

build:
  stage: build
  script:
    - wget -O yopass-upstream.tar.gz https://codeload.github.com/jhaals/yopass/tar.gz/$YOPASS_UPSTREAM_VERSION
    - tar xzf yopass-upstream.tar.gz
    - mv $CI_PROJECT_DIR/website $CI_PROJECT_DIR/changes
    - mv $CI_PROJECT_DIR/yopass-$YOPASS_UPSTREAM_VERSION/website/ $CI_PROJECT_DIR/website/
    - mv -f $CI_PROJECT_DIR/changes/src/App.tsx $CI_PROJECT_DIR/website/src/App.tsx
    - mv -f $CI_PROJECT_DIR/changes/public/index.html $CI_PROJECT_DIR/website/public/index.html
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
  artifacts:
    expire_in: 15 minutes
    when: on_failure
    paths:
    - $CI_PROJECT_DIR

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
```
