### ISSUE TITLE
Add documentation for configuring via ENV Vars

### ISSUE THREAD

**Issue by 24367dfa** [jhaals/yopass#2122]
[Here](https://github.com/jhaals/yopass/blob/master/cmd/yopass-server/main.go#L35) i saw that yopass loads configuration from the environment.

I tested it with a simple docker-compose file and would like to add some documentation to the README.

```
services:
...
  yopass:
    image: jhaals/yopass
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - MAX_LENGTH=1000
      - PORT=8080
      - MEMCACHED=memcached:11211
...
```

PS: [viper](https://github.com/spf13/viper?tab=readme-ov-file#working-with-environment-variables) has a function to define an application specific env-var prefix, that might be an option to avoid name conflicts.
