### ISSUE TITLE
New env var prefix seems like a breaking change

### ISSUE THREAD

**Issue by psalaberria002** [jhaals/yopass#2760]
Introduced in https://github.com/jhaals/yopass/pull/2143

Env vars such as the following do not work anymore:
```
          env:
            - name: DATABASE
              value: redis
            - name: REDIS
              value: redis://127.0.0.1:6379/0
```

In addition,  when running Yopass in Kubernetes, and the name of the service is set to yopass, then Kubernetes will automatically inject a bunch of variables to the pod.

For example I get the following:
```
YOPASS_SERVICE_PORT=80
YOPASS_PORT_80_TCP=tcp://10.100.11.235:80
YOPASS_PORT_80_TCP_PROTO=tcp
YOPASS_PORT_80_TCP_PORT=80
YOPASS_SERVICE_PORT_HTTP=80
YOPASS_SERVICE_HOST=10.100.11.235
YOPASS_PORT_80_TCP_ADDR=10.100.11.235
YOPASS_PORT=tcp://10.100.11.235:80
```

Yopass tries to set the port number based on `YOPASS_PORT`, which is totally wrong in this case. As you can see, it sets it to zero.
```
{"level":"info","ts":1743159341.978982,"caller":"yopass-server/main.go:76","msg":"Starting yopass server","address":":0"}
```

I can work around it by specifying the `--port` cli arg, but this seems like a breaking change for those running in Kubernetes.
